- hosts: master
  vars_prompt:
    - name: username
      prompt: 'Enter username for traefik'
      private: no

    - name: password
      prompt: 'Enter password for traefik'

    - name: email
      prompt: 'Enter email for traefik'
      private: no

    - name: domain
      prompt: 'Enter domain for traefik'
      private: no

  tasks:
    - name: Copy traefik dir
      synchronize:
        src: .
        dest: .

    - name: Create hashed password
      shell: 'openssl passwd -apr1 {{ password }}'
      register: hashed_password_raw

    - name: save hashed password
      set_fact:
        hashed_password: '{{ hashed_password_raw.stdout_lines[0] }}'

    - name: Add traefik label for master node
      shell: 'docker node update --label-add traefik-public.traefik-public-certificates=true master'

    - name: Create traefik network
      shell: 'docker network create --driver=overlay traefik-public > create_traefik_network.txt'
      args:
        chdir: $HOME
        creates: create_traefik_network.txt

    - name: Deploy traefik
      shell: 'docker stack deploy -c traefik/docker-compose.yml traefik'
      environment:
        - USERNAME: '{{ username }}'
        - HASHED_PASSWORD: '{{ hashed_password }}'
        - EMAIL: '{{ email }}'
        - DOMAIN: '{{ domain }}'
      args:
        chdir: $HOME
